import type { ComponentType } from "react";
import {
  Sparkles,
  ArrowRight,
  Play,
  Shield,
  Gauge,
  Zap,
  Rocket,
  Target,
  Lightbulb,
  Layout,
  Code2,
  Beaker,
  Globe2,
  LayoutDashboard,
  Cpu,
  Briefcase,
  BarChart3,
  Users2,
  ShoppingCart,
  ChevronRight,
  HelpCircle,
  ChevronDown,
  Twitter,
  Github,
  Linkedin,
  Mail,
  Phone,
} from "lucide-react";

export type IconComponent = ComponentType<{ className?: string }>;

export const ICONS = {
  sparkles: Sparkles,
  arrowRight: ArrowRight,
  play: Play,
  shield: Shield,
  gauge: Gauge,
  zap: Zap,
  rocket: Rocket,
  target: Target,
  lightbulb: Lightbulb,
  layout: Layout,
  code2: Code2,
  beaker: Beaker,
  globe2: Globe2,
  layoutDashboard: LayoutDashboard,
  cpu: Cpu,
  briefcase: Briefcase,
  barChart3: BarChart3,
  users2: Users2,
  shoppingCart: ShoppingCart,
  chevronRight: ChevronRight,
  helpCircle: HelpCircle,
  chevronDown: ChevronDown,
  twitter: Twitter,
  github: Github,
  linkedin: Linkedin,
  mail: Mail,
  phone: Phone,
} as const;

export type IconName = keyof typeof ICONS;

export function getIcon(name: string): IconComponent {
  return (ICONS as Record<string, IconComponent>)[name] ?? Sparkles;
}

export {
  Sparkles,
  ArrowRight,
  Play,
  Shield,
  Gauge,
  Zap,
  Rocket,
  Target,
  Lightbulb,
  Layout,
  Code2,
  Beaker,
  Globe2,
  LayoutDashboard,
  Cpu,
  Briefcase,
  BarChart3,
  Users2,
  ShoppingCart,
  ChevronRight,
  HelpCircle,
  ChevronDown,
  Twitter,
  Github,
  Linkedin,
  Mail,
  Phone,
};
